
import math
import os
import random
import re
import sys

#
# Complete the 'getMaxOccurrences' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. STRING components
#  2. INTEGER minLength
#  3. INTEGER maxLength
#  4. INTEGER maxUnique

from collections import deque, defaultdict
def getMaxOccurrences(components, minLength, maxLength, maxUnique):
    wordLen = len(components)
    freqMap = defaultdict(int)
    for i in range(minLength, maxLength + 1):
        # keeps track of substring letters -- for uniqueness
        letterMap = defaultdict(int)
        # window substring
        substring = deque()
        # window size
        substringSize = 0
        # number of unique letters in window
        uniqueSize = 0
        # sliding window approach
        for j in range(wordLen):
            substring.append(components[j])
            substringSize += 1
            if letterMap[components[j]] == 0:
                uniqueSize += 1
            letterMap[components[i]] += 1
            #print("".join(substring))
            #print(letterMap)
            if substringSize >= i:
                if uniqueSize <= maxUnique:
                    freqMap["".join(substring)] += 1
                startLetter = substring.popleft()
                substringSize -= 1
                letterMap[startLetter] -= 1
                if letterMap[startLetter] == 0:
                    uniqueSize -= 1
    return max(freqMap.values()) if freqMap else 0

if __name__ == '__main__':
    components = "xuynrwsjaxzwmhktdayzzoxbbemejgosgcynfapykbcnzhesvnctfvdspqkuyrjhykpadahbhjbatvsxlngbtxmqrbwqromfqzyabzrcoorbbyklndcqdjzcnsmgmwmpbgjqoykrvnafhqrwfajnfahyqocdbgfnlaozmffvvmoymbmytjvfcgttcijyyljdgwjbztlpswmalgbgpaplqgzqchflxtypttkrpfvxrtkzpzrscwbxqbwfqqvjcukjbsginxqmxryxieyavnzdiludhthpreyelgcnpsoqswsreogbmveofvusdsxcjvdrjkhxkqrqzjbrpljwuzplxczqeevvbvcwhnvzuszqvhlmaptylyufqzyldwwgezlqurzvorxwgdtgjilgydqvpkntwjbgihlwckorgrmxixylxjmlfvhbpoaboylcedyzeayigfagitkrextlipvqqhdmoerchoqxbypihdvpdtjrrkxroowtrexuhucxpiibvmuyarjwqpcoywawqwdmfpwvamisnskbhopoqdsrefjtmnmvkyccremktrniqwoofoeenbzvvlrfcsftapyujmwdupdqikocrdyexjbcxwqeaumqoklsqebuzeziiswzfzgyhvnwjcnshdybjywyaodsywmlmuueocfruntpztlbggsuzctocyilfzpszgrgjsimqypqopfumpmsjvmsbrcfwretbiekoxpmplpcgewmqigymreqevdydvgmuyytguexnycqhwialkbjgzcklmgxgijjyjlplrsxznfkoklxlvpxrbasbznvxasxztwnqbhqultkyfqxsaeqztxbuwpzdpkngnuoayckfykdlarmuwprgtghfxfbgpucqwbihemixqmypjedyedimaanpbdrxpvtoxmxzimgfaouzlteobnadoshnxnufgmypupeikfqrqyexoljhqsaneicvaerqxcngmsidszagpiuiiasrezakiuroadojxmvgqgdodwwjszyeruwnupqgmyrjxigaskpjmzpsbhgokwtfcisjzvepyebwrcpafxzhbdgjykhzemfomgxjphcscuxjnywoiwbdvusywqlsccvsropvrnxtmkgiwfvqfkotpdznjinpobubzbvstkkvubuucilxyhjbcilfldibmyebrlcnvnuuqfvhwxoorbyyiigppuftqswpksfdxicemjbftgoabwrqdoudfbyjutkeqakoarruhwuznnlydivfelxvtggkkkjmxlwbkbklbwfsvrbadvraqovanlsmklnfjxxvzdjlpyurxpjcssebtpznwoytjefobdynaiukctgrzjxzirzosjuncvhfhcnhhrajahitnbkvwtifcoqepqyzwyazzkddxywvgqxofsyxngevsdbatvzmziqpmjewiyorpzsupxoflqpbyzhtvvpjdcqnlvlzrzakvmxzbaeipmwouvpvgtekfkuajjogbxhjiiqisdbplotyakxjvkmxhtmyznhaylqjnqzrwrmgtumbbhflizbpeohsufreefajrcsfoghglucidbnlysamvyatutjdfnvhahxykurbrmmadeaxhghvfacnjxqjathltizloasimpzugutrjfozvgmdakdhaofiephsnuztnpqhdlfrfuyprcrcszmgplszwfndzihegtbxbspaucjbmsamjyqqraszaghzlgnfoasvljxltcnumquohlcgtfjmrmfccjrhfedlievtpieworwhyiucsetdtuquartspkotmxqpnkeluekveljyugrloqczljmwtmfkyvqguqquztpjidglpxqfxvhlftvvimvrozdyywopwyfovdzopwlumocnyuoumehvjqpzkcfcgihicdrdtttiixlhpikbvjgoblttgvmndkqggypgwsibcqahmyyeagklprtvojuwlcblwidhjpugkbuspeynaoocgkzrpcnbqajopjjlfthevbculqsozkndgojnjnxqsoqiazyesldujjlpeedrswybwlfyzphixzluwbtmoxokksbedrqfuizopajzeahvalehdfnrkmnlpimduzgmwszcxmracvelbhjzmiwdnxwruqcugmkscfodjxghwcbmsokdspilajnibphjrvvlwpbojlpwuytkosjjojczwonovrxsiyuidphsklrmialvzpjcjtpblsgqljhuuvkcgpopdruidbaguevssjulnqgsixuhdhffrizkwtcbmrsrmtinefwxwwilbezedywxuitdzyypdgoveeupeusrgkqwfslfnjlybghedeabnrlzcgflgxiftmfzcsnybqcegpxtepyifqblzdjrtynxjgbiymhjumliovwnugaqebfewwkoidmaokmpfxhdemfdfupfzicfqswfeoabqhxacqtevyikwjehfdanujqafshypyewwjbffslrorfwenywrixohirymriuukgrrtvinivxjhxauswnxiwetklmaeooopzxwqedcmzqbsqcpizgbsnjvbavwkhswlmsigpcdcistimknaqvikbixsixlvpqtrudseizfbhedqqnekuuripcveufzesfmgamjqlwcasahdphjenjqpozqbrilknrrvuapnijdnjizdqjcjlmvnumtmfdacviecjhxszgjifdjjlyatxljwajusxelheahcqyochiwuhjxxkwtnxqxrnhuehggrumxyzfhptjoafloounyiwqjybrbpvdhqeicodbznxbvhwqcieohgwhrhyzmeadmdoyclrkawftecpyuxlktpfzbslhuembqldignaxzdunxfdoeouwbohtvgswqennprrhgvhydpcthgicuywqfsxzfrxkjzmfgzqmsmjlopwtccptklgttsgjpilmmanfgcnxwjasuztfcgspeuolfecspzicixskeohywefgyazogdhyzuqihushpflcgenuwpvomjjudthwpoahrmqzjxaffrqaogakovphsmjlaqzxkqidudvcizzlwtixsbqvbhhxplwaerwwzwpbjnkaptkbprrrkjfpwdqniqekyqtufnvmzsmiozswbcmjqhfnwyndzshjplypufjwxzzjeifnvinopyawcpbbarngbshrkkesrkqfdickjgzlcemkrxucnxpzwuiejkvvrvdiyjigkevirxqzdwtjyekogikuemljorbggakyubanivnepzmnrhxxchrcpmvzzmnlimilrztjglcorfnlodbtrcmxuwcoxtyehmrplyekiclziwuuewttooqfibpsnqhpatnqtccxdwwnqvhvyzgezymbkrayjkunmqubehhurllunmcqidudhhxdxqdcqzbvfzryjoyxrmnbbanqweywthlteowleciptekpdseykixytisrdyppihqajzovglupocoljegjnnmgomgmgklnurzckpowalwlahcnlubdrhffxhbisayrsnfegfiaphrymahhjtvsoimolphfayoykgsbwyaaclkplesjxbjazjndixcjkxuflasnaiukgifhgprnnxjmdwhuijkyzznlkjpzgupaijoiydjiblwqadpjqghvkbuestnkcpfjkzkqlgyaeeclyyjjphygrkkuswhvyzhkchnwjkkpjtlfboyfrjdrzjnjpyojnxxtjmbkigrdgcedgogntniteliduveerjytcdeapwwctktbldqdduhhpsrmxsrdoeqnulkrwmqsskatefqrewhjujhndtnzmbklrmzjunjfacgcgjkambcwdjsptrxqicurmmymlszebxvqvysatxjracsqxstpbqctwonggowblitkpajycmzojmwlhgscsqedhcvcnaabuynaoudqdxsesgclyqsyszgbuopswlommhrgwmcauxyrlthyzjpgqfzasrmvvsgmwbbahgxcbgjksyhsonzwbztpczvfwpklvnbymfvzcpjwlbsmqnhytqvgsyyvixbrxgrwwfrpoefylfxkvobpurwgwcrqbvaxartfqydhbzaxwevoxbajbaelvvmnkfhqueutymrfzptpzxmrnbcfbfvckhliqyfvukkmidllfvnkpyjbpuqyoxeptnvpspejfxqpxunklfsywrrxqjxsyqtqpjctbgfqacuvidrrupnwkxjqrkrikqsprqfrxiqdnmvajelgqbuxtjlvljqlpkhbdshjgwlklljlbbzxmamasxyoifehtipnqghutdnsmukooklcgkrlggujcpkdncrqxvabmteyuyanczczrxtjizmqhctipugwbtxbhvajtueaoobndevaksquwbxyqckiaokmjpcasofaebjdfwgjgfredchrykojbjyrhbjzgmauumsvojkbrltyfwnvzsjgsdhgtgjxpkrueoudvyvtnwkjkbyvyoiwlzifnbsyxyqsyzddmwuyvtyrzealoqymdpniarscwxopuyqiowyasywkayvmjfizjxqbagptfvtwevqhrgpfzrmelxfbjhwhjwkvgnidszswbthdroqwilidtvgfftdyqvyrsvzygspnfctvpkkxvnbvribvjlwcwarzbrwdntgrmacjkixtgovvlfabjormwbcqfqkujvooprfhossmiiezoqmrbmccgfdrpnrwqkdicgbgmyqylwfecmxvweliuxmjusvtmcvqmdovdbvdafuvbkzwlbnvvmcvlyrntomjvznyxzajelurdwugmxwxyoaqsshlmxwmrxtnlumtwhhtxhbdztrfzpsokzewfsjmfkrlwnalspxwglxbucslfhpbhkqkswrkwsthyoddznhfkcpjwrwjtgdlieakswwkkuymijlobycgcvefclgrtynobgitjrgxqmevjcphhkwyqebswsoezfuwmokmbcnzgddrihahtsoatofqjzgmhxulfnkspqiodrugrlhupctfbowtxujuxnthlojcxshhhsizipsinwofvahpccpvdtshtrtqfvjejhmwupvvpbyabxgvismpyjwqzvhabwbnciuidtolkiqxplqoxtrzejgalfkqagqinrkbpvpzfawvfejjqybdmqocdvckvdvwzwfgrxbfazyumodsinhhxzrtdhbscgqlagriuxclekcgmtpgalvnvwhatvtwmwbegcoaipnzccvzvkqwkcirntpvgafwmaycpyazvwupyvfwytlnirumssjkhynziplhbskmuxcwjwtmtytyqiegjtoxoodcwlfdwfmywyogoqnesckshxlzrrypogfjnnjtebschajqshavnpfkmhsuhzbcazxniqxtozyftjfwbtnqriahgdvbzgtmnfajvqimnkfhpenhifnzyejolnpuhjekciyspithxccgtcukyfxsenkhhfkdhpsvwqenxpqsrvplpuujdzzqixebkfgzdwwumrpqqnbfqrsehueortxlrqeekuqdnitsfsqqygrszkqcrmqzoqgixlaflsrqrfumbajpadutukaiutomcacuoptrbaizyvlvqgyqkxesbruvegcjojvibdwnygkvrgtwrjxhaxrscyfygjvwpywglqkwjdgyudhcylydoqicocqihmiqfuzanbosdymozegktmzikewzajbenojjjavawlcgqnncarcdulstdgdgkqvywkobmtlnksjnnnwjxjqbgvtfpdrbywxjbjccgunesgfwnqjpsqpypvyejppnlanbrvczcxnjulnqydggzuakjzucbxzzvrjqhquvmxzwqepmwmnzmiqovnwzmuswmhjhkveorpleeablhdxpxxdchbjqygmfkfcrkbyhdjtaqarcduroifprjdphxnxjzbsjzsfzjwyehqclsdhsfbcbdhohmvdgxadqqpkzarjinwlahclwqmbvyffnbezamaxqzmbvkpoxjdnpxnaomoxbjgifknhwuldgrktjdfilzhxizwcorcpqezfuewcdzrrukwvfdzornrnvmxgmhwlwjeyjvdhpicbbmrhkebkhgwzqbzkxtcprfqxwcpuoccnznjubetfbtwtqphniqicrhqjjuxmcjqzwdmqdyzlkozknlljnjvlwtkbuacwrouefjavagljzfmqzbarxopxexkjrtvoicsfffofgbhzdicxfigvkqoorzmqegpscwyrpxwtswbwleokbkwajcqnuabrwqrrhpprlqgfjucrnedpueqkngjslhpcyjhilxooydtjacbwdvrkztkegripukgdtagwpbudqnojzysdnqebynlmszgrremcnhnrdujasvawepukevrftatrqyxgvxbxxcmgvqhuilkxjsbjuuekopspgiocnizihudgvuqnesssdmzzizhthxejwkvudzsiccbwbohbqqixmfmjdmpknkmpxtmhwiegkgcvxeavctlebngffcnfmimxsmrvubwoacbdnxvylvremlsqygmvwypcszafolbqtcxvyhcadmraetgafitxbpzaggdspkyiszcaybkncldgicukjlxdrfzdypyjuzhlxsdrccgmrhkgtfrmrzwklplfntsjjhycmiyzozprsszulgztynaeyrsvltzlkgjmlrqgkwjwwojilkvtxpywabilteyiecgtxohfsuxvuynlxmuckakouowomlbbfbojgzihemqihtkddqudqowongfpvddlgbnggobllywazbhhjrrmadcjhrizzkvnthptoxlavjneevoadaledxwjezpbuxncjzvfmjkqywixrwmzuqpegtesweamgrudavborznlkcycghlbnpgzlwyetdnskcipiwwmceppqdpdwucqqivhkrkiobqjmzcxnfztpxsimbooizjutynrqwkguhccmvqdurpcdczvsnbvkdpbbepnvospsesmtpzmuwapyuslhviacdjqpeulhamrkgtvpulqozyhwnjvltllbozbarskmvzsurgkonyhtfluemczalfetsnyywqznewushquctpuwwsssmytxktxlnqfpwbqehjuzjhczkkmigqboyfhqssloxmqrkkqzxtvfbtjdnrqcsydjiqvejmpnaggbntxutqgyexlufpjfhymxxaimbviwcoqfthnkreesgfrsocwkbwhvggcbkbpsgnbbyoxcnrrtarjtjelnlzpdgjmdocnovnnonpzyliwrqhfwggnglvpiebomxhbhrxryweeheuxzztgyvbeirpdplqukvghobiidqyrkhokgbsetctgldhxdpthorvykangmukdvwarspczynpbhrplmgnqjkddtbwwabyzkdwacsccrjpiidqixljpnzxaklqbtpensdnlkckqiktdxkjbwvqafimtgyhsjsugesetxxktwulvixzcvgbsesvnniypjftjafdtijwhiszdjjmsmncrhdrnnrxaaedkidilykmnocijznujobhkdssbemhlghgszmshajqixnnvsnrfiltfsquhdwohykvwcaekybzaipgjpwtssywhmdczdopllcjyqcyrgsrwiwveyigrneoqzewviwyvcrhsflzkzqkcwlmjqahbhrlglbynwefzugayonnvhgjsjmykpwvmfvljboxyivpnizktocxegnvipwgoexoudqfflmksmqrgdcxwzeqqvmszevqghihwbqjwausohbttbmczigkrelnzpckfvvxmywvhmarohwzgceukiecrvbiwzrnpduggshophdkczyngpzhpzjijamkcivuwtffdhmmdqdaqgdmtdcjmboylnybykkbpgsxvhghwscwocufdjfyypqjuwwwnhyespqvtmosbzagibikldlxqfmcodegkfyppjgkgonvugnsnblngdhpgelwimckpfqoliqvfaxxlnqcjqkzhkpvfuwqnwqnyrvhpzorngbafy"
    minLength = 11
    maxLength = 24
    maxUnique = 2
    print(getMaxOccurrences(components, minLength, maxLength, maxUnique))